apiVersion: apps/v1
kind: Deployment
metadata:
  name: fatclinic-was-deployment
  labels:
    app: fatclinic
spec:
  replicas: 3 # pod 개수 지정 
  selector:
    matchLabels:
      app: fatclinic
  template:
    metadata:
      labels:
        app: fatclinic
        tier: was
    spec:
      containers:
      - name: fatclinic-container
        image: asia.gcr.io/midyear-spot-368821/fatclinic:30
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:  
            cpu: "500m"  
---
apiVersion: v1
kind: Service
metadata:
  name: argo-lb
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
